version: '3'
services:
  visits:
    build: .
    container_name: visits
    ports: 
      - 8080:8080
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
